# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `activesupport` gem.
# Please instead update this file by running `bin/tapioca sync`.

# typed: false

class FalseClass
  include ::JSON::Ext::Generator::GeneratorMethods::FalseClass
end

class Float < ::Numeric
  include ::JSON::Ext::Generator::GeneratorMethods::Float
end

class IO
  include ::Enumerable
  include ::File::Constants
end

class IO::EAGAINWaitReadable < ::Errno::EAGAIN
  include ::IO::WaitReadable
end

class IO::EAGAINWaitWritable < ::Errno::EAGAIN
  include ::IO::WaitWritable
end

class IO::EINPROGRESSWaitReadable < ::Errno::EINPROGRESS
  include ::IO::WaitReadable
end

class IO::EINPROGRESSWaitWritable < ::Errno::EINPROGRESS
  include ::IO::WaitWritable
end

IO::EWOULDBLOCKWaitReadable = IO::EAGAINWaitReadable
IO::EWOULDBLOCKWaitWritable = IO::EAGAINWaitWritable

class Integer < ::Numeric
  include ::JSON::Ext::Generator::GeneratorMethods::Integer
end

Integer::GMP_VERSION = T.let(T.unsafe(nil), String)

class NameError < ::StandardError
  include ::DidYouMean::Correctable
end

class NilClass
  include ::JSON::Ext::Generator::GeneratorMethods::NilClass
end

class Numeric
  include ::Comparable
end

class Symbol
  include ::Comparable
end

class TrueClass
  include ::JSON::Ext::Generator::GeneratorMethods::TrueClass
end
