# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/cucumber-tag-expressions/all/cucumber-tag-expressions.rbi
#
# cucumber-tag-expressions-3.0.1

module Cucumber
end
module Cucumber::TagExpressions
end
class Cucumber::TagExpressions::Literal
  def evaluate(variables); end
  def initialize(value); end
  def to_s; end
end
class Cucumber::TagExpressions::Not
  def evaluate(variables); end
  def initialize(expression); end
  def to_s; end
end
class Cucumber::TagExpressions::Or
  def evaluate(variables); end
  def initialize(left, right); end
  def to_s; end
end
class Cucumber::TagExpressions::And
  def evaluate(variables); end
  def initialize(left, right); end
  def to_s; end
end
class Cucumber::TagExpressions::Parser
  def assoc_of(token, value); end
  def check(expected_token_type, token_type); end
  def handle_binary_operator(token, expected_token_type); end
  def handle_close_paren(_token, expected_token_type); end
  def handle_literal(token, expected_token_type); end
  def handle_open_paren(token, expected_token_type); end
  def handle_unary_operator(token, expected_token_type); end
  def initialize; end
  def lower_precedence?(operation); end
  def operator?(token); end
  def parse(infix_expression); end
  def pop(array, n = nil); end
  def precedence(token); end
  def process_tokens!(infix_expression); end
  def push_expression(token); end
  def tokens(infix_expression); end
end
