# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/cucumber-messages/all/cucumber-messages.rbi
#
# cucumber-messages-15.0.0

module Cucumber
end
module Cucumber::Messages
  def self.optionable_descriptor_class; end
  extend Protobuf::Optionable::ClassMethods
  include Protobuf::Optionable
end
class Cucumber::Messages::Envelope < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def attachment!; end
  def attachment; end
  def attachment=(v); end
  def gherkin_document!; end
  def gherkin_document; end
  def gherkin_document=(v); end
  def hook!; end
  def hook; end
  def hook=(v); end
  def meta!; end
  def meta; end
  def meta=(v); end
  def parameter_type!; end
  def parameter_type; end
  def parameter_type=(v); end
  def parse_error!; end
  def parse_error; end
  def parse_error=(v); end
  def pickle!; end
  def pickle; end
  def pickle=(v); end
  def source!; end
  def source; end
  def source=(v); end
  def step_definition!; end
  def step_definition; end
  def step_definition=(v); end
  def test_case!; end
  def test_case; end
  def test_case=(v); end
  def test_case_finished!; end
  def test_case_finished; end
  def test_case_finished=(v); end
  def test_case_started!; end
  def test_case_started; end
  def test_case_started=(v); end
  def test_run_finished!; end
  def test_run_finished; end
  def test_run_finished=(v); end
  def test_run_started!; end
  def test_run_started; end
  def test_run_started=(v); end
  def test_step_finished!; end
  def test_step_finished; end
  def test_step_finished=(v); end
  def test_step_started!; end
  def test_step_started; end
  def test_step_started=(v); end
  def undefined_parameter_type!; end
  def undefined_parameter_type; end
  def undefined_parameter_type=(v); end
  extend Cucumber::Messages::ParseDelimited
  include Cucumber::Messages::WriteDelimited
  include Cucumber::Messages::WriteNdjson
end
class Cucumber::Messages::Meta < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def ci!; end
  def ci; end
  def ci=(v); end
  def cpu!; end
  def cpu; end
  def cpu=(v); end
  def implementation!; end
  def implementation; end
  def implementation=(v); end
  def os!; end
  def os; end
  def os=(v); end
  def protocol_version!; end
  def protocol_version; end
  def protocol_version=(v); end
  def runtime!; end
  def runtime; end
  def runtime=(v); end
end
class Cucumber::Messages::Meta::Product < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def name!; end
  def name; end
  def name=(v); end
  def version!; end
  def version; end
  def version=(v); end
end
class Cucumber::Messages::Meta::CI < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def git!; end
  def git; end
  def git=(v); end
  def name!; end
  def name; end
  def name=(v); end
  def url!; end
  def url; end
  def url=(v); end
end
class Cucumber::Messages::Meta::CI::Git < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def branch!; end
  def branch; end
  def branch=(v); end
  def remote!; end
  def remote; end
  def remote=(v); end
  def revision!; end
  def revision; end
  def revision=(v); end
  def tag!; end
  def tag; end
  def tag=(v); end
end
class Cucumber::Messages::Timestamp < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def nanos!; end
  def nanos; end
  def nanos=(v); end
  def seconds!; end
  def seconds; end
  def seconds=(v); end
end
class Cucumber::Messages::Duration < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def nanos!; end
  def nanos; end
  def nanos=(v); end
  def seconds!; end
  def seconds; end
  def seconds=(v); end
end
class Cucumber::Messages::Location < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def column!; end
  def column; end
  def column=(v); end
  def line!; end
  def line; end
  def line=(v); end
end
class Cucumber::Messages::SourceReference < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def java_method!; end
  def java_method; end
  def java_method=(v); end
  def java_stack_trace_element!; end
  def java_stack_trace_element; end
  def java_stack_trace_element=(v); end
  def location!; end
  def location; end
  def location=(v); end
  def uri!; end
  def uri; end
  def uri=(v); end
end
class Cucumber::Messages::SourceReference::JavaMethod < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def class_name!; end
  def class_name; end
  def class_name=(v); end
  def method_name!; end
  def method_name; end
  def method_name=(v); end
  def method_parameter_types!; end
  def method_parameter_types; end
  def method_parameter_types=(v); end
end
class Cucumber::Messages::SourceReference::JavaStackTraceElement < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def class_name!; end
  def class_name; end
  def class_name=(v); end
  def file_name!; end
  def file_name; end
  def file_name=(v); end
  def method_name!; end
  def method_name; end
  def method_name=(v); end
end
class Cucumber::Messages::Source < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def data!; end
  def data; end
  def data=(v); end
  def media_type!; end
  def media_type; end
  def media_type=(v); end
  def uri!; end
  def uri; end
  def uri=(v); end
end
class Cucumber::Messages::GherkinDocument < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def comments!; end
  def comments; end
  def comments=(v); end
  def feature!; end
  def feature; end
  def feature=(v); end
  def uri!; end
  def uri; end
  def uri=(v); end
end
class Cucumber::Messages::GherkinDocument::Comment < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def location!; end
  def location; end
  def location=(v); end
  def text!; end
  def text; end
  def text=(v); end
end
class Cucumber::Messages::GherkinDocument::Feature < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def children!; end
  def children; end
  def children=(v); end
  def description!; end
  def description; end
  def description=(v); end
  def keyword!; end
  def keyword; end
  def keyword=(v); end
  def language!; end
  def language; end
  def language=(v); end
  def location!; end
  def location; end
  def location=(v); end
  def name!; end
  def name; end
  def name=(v); end
  def tags!; end
  def tags; end
  def tags=(v); end
end
class Cucumber::Messages::GherkinDocument::Feature::Tag < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def id!; end
  def id; end
  def id=(v); end
  def location!; end
  def location; end
  def location=(v); end
  def name!; end
  def name; end
  def name=(v); end
end
class Cucumber::Messages::GherkinDocument::Feature::FeatureChild < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def background!; end
  def background; end
  def background=(v); end
  def rule!; end
  def rule; end
  def rule=(v); end
  def scenario!; end
  def scenario; end
  def scenario=(v); end
end
class Cucumber::Messages::GherkinDocument::Feature::FeatureChild::Rule < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def children!; end
  def children; end
  def children=(v); end
  def description!; end
  def description; end
  def description=(v); end
  def id!; end
  def id; end
  def id=(v); end
  def keyword!; end
  def keyword; end
  def keyword=(v); end
  def location!; end
  def location; end
  def location=(v); end
  def name!; end
  def name; end
  def name=(v); end
  def tags!; end
  def tags; end
  def tags=(v); end
end
class Cucumber::Messages::GherkinDocument::Feature::FeatureChild::RuleChild < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def background!; end
  def background; end
  def background=(v); end
  def scenario!; end
  def scenario; end
  def scenario=(v); end
end
class Cucumber::Messages::GherkinDocument::Feature::Background < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def description!; end
  def description; end
  def description=(v); end
  def id!; end
  def id; end
  def id=(v); end
  def keyword!; end
  def keyword; end
  def keyword=(v); end
  def location!; end
  def location; end
  def location=(v); end
  def name!; end
  def name; end
  def name=(v); end
  def steps!; end
  def steps; end
  def steps=(v); end
end
class Cucumber::Messages::GherkinDocument::Feature::Scenario < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def description!; end
  def description; end
  def description=(v); end
  def examples!; end
  def examples; end
  def examples=(v); end
  def id!; end
  def id; end
  def id=(v); end
  def keyword!; end
  def keyword; end
  def keyword=(v); end
  def location!; end
  def location; end
  def location=(v); end
  def name!; end
  def name; end
  def name=(v); end
  def steps!; end
  def steps; end
  def steps=(v); end
  def tags!; end
  def tags; end
  def tags=(v); end
end
class Cucumber::Messages::GherkinDocument::Feature::Scenario::Examples < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def description!; end
  def description; end
  def description=(v); end
  def id!; end
  def id; end
  def id=(v); end
  def keyword!; end
  def keyword; end
  def keyword=(v); end
  def location!; end
  def location; end
  def location=(v); end
  def name!; end
  def name; end
  def name=(v); end
  def table_body!; end
  def table_body; end
  def table_body=(v); end
  def table_header!; end
  def table_header; end
  def table_header=(v); end
  def tags!; end
  def tags; end
  def tags=(v); end
end
class Cucumber::Messages::GherkinDocument::Feature::TableRow < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def cells!; end
  def cells; end
  def cells=(v); end
  def id!; end
  def id; end
  def id=(v); end
  def location!; end
  def location; end
  def location=(v); end
end
class Cucumber::Messages::GherkinDocument::Feature::TableRow::TableCell < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def location!; end
  def location; end
  def location=(v); end
  def value!; end
  def value; end
  def value=(v); end
end
class Cucumber::Messages::GherkinDocument::Feature::Step < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def data_table!; end
  def data_table; end
  def data_table=(v); end
  def doc_string!; end
  def doc_string; end
  def doc_string=(v); end
  def id!; end
  def id; end
  def id=(v); end
  def keyword!; end
  def keyword; end
  def keyword=(v); end
  def location!; end
  def location; end
  def location=(v); end
  def text!; end
  def text; end
  def text=(v); end
end
class Cucumber::Messages::GherkinDocument::Feature::Step::DataTable < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def location!; end
  def location; end
  def location=(v); end
  def rows!; end
  def rows; end
  def rows=(v); end
end
class Cucumber::Messages::GherkinDocument::Feature::Step::DocString < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def content!; end
  def content; end
  def content=(v); end
  def delimiter!; end
  def delimiter; end
  def delimiter=(v); end
  def location!; end
  def location; end
  def location=(v); end
  def media_type!; end
  def media_type; end
  def media_type=(v); end
end
class Cucumber::Messages::Attachment < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def body!; end
  def body; end
  def body=(v); end
  def content_encoding!; end
  def content_encoding; end
  def content_encoding=(v); end
  def file_name!; end
  def file_name; end
  def file_name=(v); end
  def media_type!; end
  def media_type; end
  def media_type=(v); end
  def source!; end
  def source; end
  def source=(v); end
  def test_case_started_id!; end
  def test_case_started_id; end
  def test_case_started_id=(v); end
  def test_step_id!; end
  def test_step_id; end
  def test_step_id=(v); end
  def url!; end
  def url; end
  def url=(v); end
end
class Cucumber::Messages::Attachment::ContentEncoding < Protobuf::Enum
end
class Cucumber::Messages::Pickle < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def ast_node_ids!; end
  def ast_node_ids; end
  def ast_node_ids=(v); end
  def id!; end
  def id; end
  def id=(v); end
  def language!; end
  def language; end
  def language=(v); end
  def name!; end
  def name; end
  def name=(v); end
  def steps!; end
  def steps; end
  def steps=(v); end
  def tags!; end
  def tags; end
  def tags=(v); end
  def uri!; end
  def uri; end
  def uri=(v); end
end
class Cucumber::Messages::Pickle::PickleTag < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def ast_node_id!; end
  def ast_node_id; end
  def ast_node_id=(v); end
  def name!; end
  def name; end
  def name=(v); end
end
class Cucumber::Messages::Pickle::PickleStep < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def argument!; end
  def argument; end
  def argument=(v); end
  def ast_node_ids!; end
  def ast_node_ids; end
  def ast_node_ids=(v); end
  def id!; end
  def id; end
  def id=(v); end
  def text!; end
  def text; end
  def text=(v); end
end
class Cucumber::Messages::PickleStepArgument < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def data_table!; end
  def data_table; end
  def data_table=(v); end
  def doc_string!; end
  def doc_string; end
  def doc_string=(v); end
end
class Cucumber::Messages::PickleStepArgument::PickleDocString < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def content!; end
  def content; end
  def content=(v); end
  def media_type!; end
  def media_type; end
  def media_type=(v); end
end
class Cucumber::Messages::PickleStepArgument::PickleTable < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def rows!; end
  def rows; end
  def rows=(v); end
end
class Cucumber::Messages::PickleStepArgument::PickleTable::PickleTableRow < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def cells!; end
  def cells; end
  def cells=(v); end
end
class Cucumber::Messages::PickleStepArgument::PickleTable::PickleTableRow::PickleTableCell < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def value!; end
  def value; end
  def value=(v); end
end
class Cucumber::Messages::TestCase < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def id!; end
  def id; end
  def id=(v); end
  def pickle_id!; end
  def pickle_id; end
  def pickle_id=(v); end
  def test_steps!; end
  def test_steps; end
  def test_steps=(v); end
end
class Cucumber::Messages::TestCase::TestStep < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def hook_id!; end
  def hook_id; end
  def hook_id=(v); end
  def id!; end
  def id; end
  def id=(v); end
  def pickle_step_id!; end
  def pickle_step_id; end
  def pickle_step_id=(v); end
  def step_definition_ids!; end
  def step_definition_ids; end
  def step_definition_ids=(v); end
  def step_match_arguments_lists!; end
  def step_match_arguments_lists; end
  def step_match_arguments_lists=(v); end
end
class Cucumber::Messages::TestCase::TestStep::StepMatchArgumentsList < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def step_match_arguments!; end
  def step_match_arguments; end
  def step_match_arguments=(v); end
end
class Cucumber::Messages::TestCase::TestStep::StepMatchArgumentsList::StepMatchArgument < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def group!; end
  def group; end
  def group=(v); end
  def parameter_type_name!; end
  def parameter_type_name; end
  def parameter_type_name=(v); end
end
class Cucumber::Messages::TestCase::TestStep::StepMatchArgumentsList::StepMatchArgument::Group < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def children!; end
  def children; end
  def children=(v); end
  def start!; end
  def start; end
  def start=(v); end
  def value!; end
  def value; end
  def value=(v); end
end
class Cucumber::Messages::TestRunStarted < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def timestamp!; end
  def timestamp; end
  def timestamp=(v); end
end
class Cucumber::Messages::TestCaseStarted < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def attempt!; end
  def attempt; end
  def attempt=(v); end
  def id!; end
  def id; end
  def id=(v); end
  def test_case_id!; end
  def test_case_id; end
  def test_case_id=(v); end
  def timestamp!; end
  def timestamp; end
  def timestamp=(v); end
end
class Cucumber::Messages::TestCaseFinished < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def test_case_started_id!; end
  def test_case_started_id; end
  def test_case_started_id=(v); end
  def timestamp!; end
  def timestamp; end
  def timestamp=(v); end
end
class Cucumber::Messages::TestStepStarted < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def test_case_started_id!; end
  def test_case_started_id; end
  def test_case_started_id=(v); end
  def test_step_id!; end
  def test_step_id; end
  def test_step_id=(v); end
  def timestamp!; end
  def timestamp; end
  def timestamp=(v); end
end
class Cucumber::Messages::TestStepFinished < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def test_case_started_id!; end
  def test_case_started_id; end
  def test_case_started_id=(v); end
  def test_step_id!; end
  def test_step_id; end
  def test_step_id=(v); end
  def test_step_result!; end
  def test_step_result; end
  def test_step_result=(v); end
  def timestamp!; end
  def timestamp; end
  def timestamp=(v); end
end
class Cucumber::Messages::TestStepFinished::TestStepResult < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def duration!; end
  def duration; end
  def duration=(v); end
  def message!; end
  def message; end
  def message=(v); end
  def status!; end
  def status; end
  def status=(v); end
  def will_be_retried!; end
  def will_be_retried; end
  def will_be_retried=(v); end
  def will_be_retried?; end
end
class Cucumber::Messages::TestStepFinished::TestStepResult::Status < Protobuf::Enum
end
class Cucumber::Messages::TestRunFinished < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def message!; end
  def message; end
  def message=(v); end
  def success!; end
  def success; end
  def success=(v); end
  def success?; end
  def timestamp!; end
  def timestamp; end
  def timestamp=(v); end
end
class Cucumber::Messages::Hook < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def id!; end
  def id; end
  def id=(v); end
  def source_reference!; end
  def source_reference; end
  def source_reference=(v); end
  def tag_expression!; end
  def tag_expression; end
  def tag_expression=(v); end
end
class Cucumber::Messages::StepDefinition < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def id!; end
  def id; end
  def id=(v); end
  def pattern!; end
  def pattern; end
  def pattern=(v); end
  def source_reference!; end
  def source_reference; end
  def source_reference=(v); end
end
class Cucumber::Messages::StepDefinition::StepDefinitionPattern < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def source!; end
  def source; end
  def source=(v); end
  def type!; end
  def type; end
  def type=(v); end
end
class Cucumber::Messages::StepDefinition::StepDefinitionPattern::StepDefinitionPatternType < Protobuf::Enum
end
class Cucumber::Messages::ParameterType < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def id!; end
  def id; end
  def id=(v); end
  def name!; end
  def name; end
  def name=(v); end
  def prefer_for_regular_expression_match!; end
  def prefer_for_regular_expression_match; end
  def prefer_for_regular_expression_match=(v); end
  def prefer_for_regular_expression_match?; end
  def regular_expressions!; end
  def regular_expressions; end
  def regular_expressions=(v); end
  def use_for_snippets!; end
  def use_for_snippets; end
  def use_for_snippets=(v); end
  def use_for_snippets?; end
end
class Cucumber::Messages::UndefinedParameterType < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def expression!; end
  def expression; end
  def expression=(v); end
  def name!; end
  def name; end
  def name=(v); end
end
class Cucumber::Messages::ParseError < Protobuf::Message
  def _protobuf_message_field; end
  def _protobuf_message_unset_required_field_tags; end
  def message!; end
  def message; end
  def message=(v); end
  def source!; end
  def source; end
  def source=(v); end
end
module Cucumber::Messages::Varint
  def self.decode_varint(io); end
  def self.encode_varint(io, int_val); end
end
class Cucumber::Messages::BinaryToMessageEnumerator < Enumerator
  def initialize(io); end
end
class Cucumber::Messages::NdjsonToMessageEnumerator < Enumerator
  def initialize(io); end
end
module Cucumber::Messages::WriteDelimited
  def write_delimited_to(io); end
end
module Cucumber::Messages::ParseDelimited
  def parse_delimited_from(io); end
end
module Cucumber::Messages::WriteNdjson
  def write_ndjson_to(io); end
end
module Cucumber::Messages::TimeConversion
  def duration_to_seconds(duration); end
  def seconds_to_duration(seconds_float); end
  def time_to_timestamp(time); end
  def timestamp_to_time(timestamp); end
end
module Cucumber::Messages::IdGenerator
end
class Cucumber::Messages::IdGenerator::Incrementing
  def initialize; end
  def new_id; end
end
class Cucumber::Messages::IdGenerator::UUID
  def new_id; end
end
