# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/cucumber-create-meta/all/cucumber-create-meta.rbi
#
# cucumber-create-meta-4.0.0

module Cucumber
end
module Cucumber::CreateMeta
  def create_ci(ci_name, ci_system, env); end
  def create_meta(tool_name, tool_version, env = nil); end
  def detect_ci(env); end
  def evaluate(template, env); end
  def group1(value, regexp); end
  def remove_userinfo_from_url(value); end
  def self.create_ci(ci_name, ci_system, env); end
  def self.create_meta(tool_name, tool_version, env = nil); end
  def self.detect_ci(env); end
  def self.evaluate(template, env); end
  def self.group1(value, regexp); end
  def self.remove_userinfo_from_url(value); end
end
