# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ruby-next-core` gem.
# Please instead update this file by running `bin/tapioca sync`.

# typed: true

class NoMatchingPatternError < ::RuntimeError; end
