# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/tapioca/all/tapioca.rbi
#
# tapioca-0.4.23

module Tapioca
  def self.silence_warnings(&blk); end
end
module Tapioca::Compilers
end
module Tapioca::Compilers::Dsl
end
class Tapioca::Compilers::Dsl::Base
  def compile_method_parameters_to_parlour(*args, &blk); end
  def compile_method_return_type_to_parlour(*args, &blk); end
  def create_method(*args, &blk); end
  def create_method_from_def(*args, &blk); end
  def decorate(*args, &blk); end
  def gather_constants(*args, &blk); end
  def handles?(*args, &blk); end
  def initialize(*args, &blk); end
  def parameters_types_from_signature(*args, &blk); end
  def processable_constants(*args, &blk); end
  def valid_method_name?(*args, &blk); end
  extend T::Helpers
  extend T::InterfaceWrapper::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Tapioca::Error < StandardError
end
