# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/tracker_api/all/tracker_api.rbi
#
# tracker_api-1.13.0

module TrackerApi
end
class TrackerApi::Error < StandardError
  def faraday_response_error?(wrapped_exception); end
  def initialize(wrapped_exception); end
  def response; end
  def wrapped_exception; end
end
module TrackerApi::Errors
end
class TrackerApi::Errors::UnexpectedData < StandardError
end
class TrackerApi::Errors::ClientError < TrackerApi::Error
end
class TrackerApi::Errors::ServerError < TrackerApi::Error
end
module TrackerApi::Endpoints
end
module TrackerApi::Resources
end
module TrackerApi::Resources::Shared
end
