# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/tty-platform/all/tty-platform.rbi
#
# tty-platform-0.1.0

module TTY
end
class TTY::Platform
  def architecture; end
  def cpu; end
  def detect_system_properties(arch); end
  def find_os_and_version(system); end
  def initialize(arch = nil); end
  def linux?; end
  def mac?; end
  def match_os?(matcher); end
  def os; end
  def to_a; end
  def to_s; end
  def unix?; end
  def version; end
  def windows?; end
  def windows_file_path?; end
end
class Class < Module
  def linux?; end
  def mac?; end
  def unix?; end
  def windows?; end
end
