# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/tty-spinner/all/tty-spinner.rbi
#
# tty-spinner-0.2.0

module TTY
end
class TTY::Spinner
  def clear_line; end
  def duration; end
  def emit(name, *args); end
  def error(stop_message = nil); end
  def error?; end
  def fetch_format(token, property); end
  def format; end
  def hide_cursor; end
  def initialize(*args); end
  def join(timeout = nil); end
  def kill; end
  def message; end
  def on(name, &block); end
  def output; end
  def reset; end
  def spin; end
  def spinning?; end
  def start; end
  def stop(stop_message = nil); end
  def success(stop_message = nil); end
  def success?; end
  def write(data, clear_first = nil); end
  include TTY::Formats
end
module TTY::Formats
end
