# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/tty-color/all/tty-color.rbi
#
# tty-color-0.3.0

module TTY
end
module TTY::Color
  def color?; end
  def mode; end
  def output; end
  def output=(arg0); end
  def supports?; end
  def supports_color?; end
  def tty?; end
  def verbose; end
  def verbose=(arg0); end
  extend TTY::Color
end
class TTY::Color::Support
  def from_curses(curses_class = nil); end
  def from_env; end
  def from_term; end
  def from_tput; end
  def initialize(env, options = nil); end
  def supports?; end
end
class TTY::Color::Mode
  def from_term; end
  def from_tput; end
  def initialize(env); end
  def mode; end
end
module TTY::Color::NoValue
end
