# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/tty-pager/all/tty-pager.rbi
#
# tty-pager-0.4.0

module TTY
end
class TTY::Pager
  def default_prompt; end
  def enabled?; end
  def find_available; end
  def initialize(options = nil); end
  def input; end
  def output; end
  def page(text, &callback); end
  def page_height; end
  def page_width; end
  def pager; end
  def self.jruby?; end
end
class TTY::Pager::BasicPager < TTY::Pager
  def continue_paging?(page_num); end
  def page(text, &callback); end
end
class TTY::Pager::NullPager < TTY::Pager
  def page(text, &callback); end
end
class TTY::Pager::SystemPager < TTY::Pager
  def page(text, &callback); end
  def pager_command(*commands); end
  def self.available(*commands); end
  def self.available?(*commands); end
  def self.command_exists?(command); end
  def self.executables; end
end
