# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/tty-which/all/tty-which.rbi
#
# tty-which-0.1.0

module TTY
end
module TTY::Which
  def executable_file?(filename, dir = nil); end
  def executable_file_with_ext?(filename); end
  def extensions(path_ext = nil); end
  def path_with_executable_file?(cmd); end
  def search_paths; end
  def which(cmd, search_path = nil); end
  extend TTY::Which
end
