# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/tty-screen/all/tty-screen.rbi
#
# tty-screen-0.5.1

module TTY
end
class TTY::Screen
  def columns; end
  def height; end
  def initialize(options = nil); end
  def rows; end
  def self.height; end
  def self.size; end
  def self.width; end
  def size; end
  def width; end
end
class TTY::Screen::Size
  def default_size; end
  def from_ansicon; end
  def from_env; end
  def from_io_console; end
  def from_readline; end
  def from_stty; end
  def from_tput; end
  def initialize(env, options = nil); end
  def jruby?; end
  def nonzero_column?(column); end
  def output; end
  def run_command(*args); end
  def size; end
  def try_io_console; end
end
